modelname: metatemos
_target_: teach.model.metatemos.METATEMOS

latent_dim: 256
vae: true

transforms: ${transforms}

ff_size: 1024
num_layers: 6
num_head: ${model.num_layers}
droupout: 0.1
activation: "gelu"
nvids_to_save: 5
#${callback.render.nvids_to_save}
lr_scheduler: null

defaults:
  - textencoder: distilbert_transformer
  - motionencoder: actor
  - motiondecoder: metactor # metactor2, metactor
  - losses: temos
  - optim: adamw
  - /model/losses/function/smoothL1@func_recons
  - /model/losses/function/smoothL1@func_latent
  - /model/losses/function/kl@func_kl
