modelname: metatemos2
_target_: teach.model.metatemos2.METATEMOS2

latent_dim: 256
vae: true

transforms: ${transforms}

ff_size: 1024
num_layers: 6
num_head: ${model.num_layers}
droupout: 0.1
activation: "gelu"
nvids_to_save: 5
#${callback.render.nvids_to_save}
lr_scheduler: null
# motion branch
motion_branch: False

defaults:
  - textencoder: distilbert_transformer
  - motionencoder: actor
  - motiondecoder: metactor2 
  - losses: teach
  - optim: adamw
  - /model/losses/function/recons@func_recons
  - /model/losses/function/recons@func_latent
  - /model/losses/function/kl@func_kl
