name: meta_actor_decoder
_target_: teach.model.motiondecoder.MetaActorDecoder

latent_dim: ${model.latent_dim}

ff_size: ${model.ff_size}
num_layers: ${model.num_layers}
num_head: ${model.num_head}
droupout: ${model.droupout}
activation: ${model.activation}

mode: posencoding