hydra:
  run:
    dir: .
  output_subdir: null

seed: 1234
logger_level: INFO

infolder: ???
outfolder: ???

# Composing nested config with default
defaults:
  - machine: server
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_
