hydra:
  run:
    dir: .
  output_subdir: null

folder: ???
split: val

mean: false
number_of_samples: 1
fact: 1
eval_pairs: false

slerp: false
checkpoint: last
align: false
jointstype: mmmns
naive: false
logger_level: INFO

defaults:
  - data: null
  - /path@path
  - /transforms/rots2joints/smplh@rots2joints
  - sampler: all_conseq
  - override hydra/job_logging: console
  - override hydra/hydra_logging: console
  - _self_

data:
  mode: 'inference'

machine:
  smpl_batch_size: 256