hydra:
  run:
    dir: ${project}/${data.dataname}/${experiment}/${run_id}
  job:
    # chdir: true
    env_set:
      # WANDB_API_KEY: ''
      PYOPENGL_PLATFORM: 'egl'
    
# Global configurations shared between different modules
experiment: training
# must be the same when you are resuming experiment
project: temos
seed: 42

# For finetuning
resume: null

logger_level: INFO
run_id: ${generate_id:}

# Composing nested config with default
defaults:
  - data: babel-amass
  - model: temos
  - machine: server
  - trainer: base
  - sampler: variable_conseq # cut it
  - logger: none
  - callback: base
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

data:
  transforms:
    normalization: true

transforms: ${data.transforms}
