_target_: teach.model.losses.TeachComputeLosses

mode: ${transforms.ename}

# Loss terms
# loss on the transition part
loss_on_transition: true
loss_on_velocities: false

## Reconstruction losses
lmd_rfeats_recons: 1.0
lmd_jfeats_recons: 1.0
lmd_vel_recons: 0.5

## Latent spaces losses
lmd_latent: 1e-5
lmd_kl: 1e-5

# Ablations
loss_on_both: true
# loss on joint position features
loss_on_jfeats: false

# Text => rfeats (rotation features)
recons_text2rfeats_vel_0: ${.lmd_vel_recons}
recons_text2rfeats_vel_1: ${.lmd_vel_recons}
recons_text2rfeats_vel_0_func: ${model.func_recons}
recons_text2rfeats_vel_1_func: ${model.func_recons}

# Text => rfeats (rotation features)
recons_text2rfeats_0: ${.lmd_rfeats_recons}
recons_text2rfeats_1: ${.lmd_rfeats_recons}
recons_text2rfeats_0_func: ${model.func_recons}
recons_text2rfeats_1_func: ${model.func_recons}

# Text => jfeats (xyz features)
recons_text2jfeats_0: ${.lmd_jfeats_recons}
recons_text2jfeats_1: ${.lmd_jfeats_recons}
recons_text2jfeats_0_func: ${model.func_recons}
recons_text2jfeats_1_func: ${model.func_recons}

# rfeats => rfeats
recons_rfeats2rfeats_0: ${.lmd_rfeats_recons}
recons_rfeats2rfeats_1: ${.lmd_rfeats_recons}
recons_rfeats2rfeats_0_func: ${model.func_recons}
recons_rfeats2rfeats_1_func: ${model.func_recons}

# jfeats => jfeats
recons_jfeats2jfeats_0: ${.lmd_jfeats_recons}
recons_jfeats2jfeats_1: ${.lmd_jfeats_recons}
recons_jfeats2jfeats_0_func: ${model.func_recons}
recons_jfeats2jfeats_1_func: ${model.func_recons}

# Latent space losses
latent_manifold_0: ${.lmd_latent}
latent_manifold_1: ${.lmd_latent}
latent_manifold_0_func: ${model.func_latent}
latent_manifold_1_func: ${model.func_latent}

# VAE losses
kl_text_0: ${.lmd_kl}
kl_text_1: ${.lmd_kl}
kl_text_0_func: ${model.func_kl}
kl_text_1_func: ${model.func_kl}

kl_motion_0: ${.lmd_kl}
kl_motion_1: ${.lmd_kl}
kl_motion_0_func: ${model.func_kl}
kl_motion_1_func: ${model.func_kl}

kl_text2motion_0: ${.lmd_kl}
kl_text2motion_1: ${.lmd_kl}
kl_text2motion_0_func: ${model.func_kl}
kl_text2motion_1_func: ${model.func_kl}

kl_motion2text_0: ${.lmd_kl}
kl_motion2text_1: ${.lmd_kl}
kl_motion2text_0_func: ${model.func_kl}
kl_motion2text_1_func: ${model.func_kl}

