modelname: teach
_target_: teach.model.teach.TEACH

latent_dim: 256
vae: true

transforms: ${transforms}

ff_size: 1024
num_layers: 6
num_head: ${model.num_layers}
droupout: 0.1
activation: "gelu"
nvids_to_save: 5
#${callback.render.nvids_to_save}
lr_scheduler: null # reduceonplateau, steplr

motion_branch: true
teacher_forcing: false
hist_frames: 5
z_prev_text: false

defaults:
  - textencoder: text_hist
  - motionencoder: actor
  - motiondecoder: actor
  - losses: teach
  - optim: adamw
  - /model/losses/function/recons@func_recons
  - /model/losses/function/recons@func_latent
  - /model/losses/function/kl@func_kl
