_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath:  ${path.working_dir}/checkpoints
filename: latest-{epoch}
monitor: step
mode: max
every_n_epochs: 100
# every_n_epochs: 5
save_top_k: -1
save_last: true
